### ISSUE TITLE
Using <outlook> after <if> has no output

### ISSUE THREAD

**Issue by sambeevors** [maizzle/framework#180] opened 2020-05-12 12:27 UTC
- Maizzle Version: 1.0.7
- Node.js Version: 10.20.1

Input
```html
<outlook>
  <xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
  <style>
    td,th,div,p,a,h1,h2,h3,h4,h5,h6 {font-family: "Segoe UI", sans-serif; mso-line-height-rule: exactly;}
  </style>
</outlook>
```

Expected output
```html
<!--[if mso|ie]>
  <xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
  <style>
    td,th,div,p,a,h1,h2,h3,h4,h5,h6 {font-family: "Segoe UI", sans-serif; mso-line-height-rule: exactly;}
  </style>
<![endif]-->
```

Actual output
**Nothing**

---

For now I'll just use the regular tags, but using the default Maizzle config the `<outlook>` tag doesn't seem to do anything. I haven't tried any of the other custom tags yet.

**Comment by sambeevors** [comment] 2020-05-12 12:30
Just to follow up on this, it seems that the conditional tags are being stripped out even if I just add them manually, so unlikely to be with the plugin itself. Setting `removeHTMLComments: false` leaves most comments in, but oddly the Outlook ones are still stripped out.

**Comment by cossssmin** [comment] 2020-05-12 12:31
It's an [ issue with`<if>` tags and HTML comments in posthtml-expressions](https://github.com/posthtml/posthtml-expressions/issues/62), hoping it'll get resolved soon.

For now, add it before any `<if>` tag (only `<if>` tags are impacted, apparently):

```html
<outlook>
    <xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
    <style>
      td,th,div,p,a,h1,h2,h3,h4,h5,h6 {font-family: Helvetica, "Segoe UI", sans-serif; mso-line-height-rule: exactly;}
    </style>
  </outlook>
  <if condition="page.title">
    <title>{{ page.title }}</title>
  </if>
```

**Comment by sambeevors** [comment] 2020-05-12 12:33
Thanks for the quick response. Happy for this to be closed as a duplicate

**Comment by cossssmin** [comment] 2020-05-12 12:36
Let's keep it around until the issue is resolved in `posthtml-expressions`.

I'll update the starter in the meanwhile, thanks for bringing it up 👍

**Comment by jsbrain** [comment] 2020-05-27 19:35
I just updated from 0.9.1 to 1.0.9 and before I was doing something like:

```html
{% if env == 'local' %}
  {% extends "src/layouts/testing.njk" %}
{% else %}
  {% extends "src/layouts/default.njk" %}
{% endif %}
```

Now I wanted to do the same with the newest version but it actually does not work.

I tried: 

```njk
<if condition="page.env === 'local'"> 
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <block name="template"></block>
  </body>
  </html>
</if>
<else>
  <div id="no-html">
    <block name="template"></block>
  </div>
</else>
```

but it does not work. It seems as if it gets confused with the 2 blocks. If I change one of them to have a different name it actually works but I cannot use the same name and change the layout only. I basically have to duplicate my template in order to use it which does not make any sense in terms of templates :D

Is this related to this initial issue or is it even another issue?

**Comment by jsbrain** [comment] 2020-06-01 13:43
@cossssmin I saw you already opened https://github.com/posthtml/posthtml-expressions/issues/82 but can you think of any workaround how I can achieve what I described in my previous post? I'm currently just using 2 files for now which both extend a different layout but that's obviously no great workflow 🙉

**Comment by cossssmin** [comment] 2020-08-14 10:41
Hey sorry I missed this! A solution would be to extend based on a condition, I think:

```html
<if condition="page.env === 'local'">
  <extends src="src/layouts/local.html">
    <block name="template">
      extending the development layout
    </block>
  </extends>
</if>
<else>
  <extends src="src/layouts/production.html">
    <block name="template">
      extending the production layout
    </block>
  </extends>
</else>
```

Unlike with Nunjucks, PostHTML uses actual nodes that it parses, so you can't mix tags like this:

```html
<if condition="page.env === 'local'">
  <extends src="src/layouts/local.html">
</if>
<else>
  <extends src="src/layouts/production.html">
</if>
    <block name="template">
      ...
    </block>
  </extends>
```

PostHTML would automatically close `<extends>` in this case, and this is what it would evaluate:

```html
<if condition="page.env === 'local'">
  <extends src="src/layouts/local.html"></extends>
</if>
<else>
  <extends src="src/layouts/production.html"></extends>
</if>
```

`<extends>` would then be empty so that's why it can't work that way, and why you need to do it with a conditional as explained in the beginning.

Doing something like this would be much better:

```html
<extends src="src/layouts/{{ page.env === 'local' ? 'master' : 'minimal' }}.html">
 ...
</extends>
```

But right now that expression isn't getting parsed, need to look into it... 🤞

**Comment by cossssmin** [comment] 2020-08-17 14:31
Hey guys, gonna close this one and keep track of it in #269 - looks like the reason for this is a bug with conditionals and text nodes in `posthtml-expressions`. Thanks!

**Closed by cossssmin** 2020-08-17 14:31 UTC

**Comment by cossssmin** [comment] 2020-08-24 12:29
Just an update in case you're not getting notifications from #269 - this should now be fixed in [`v1.4.2`](https://github.com/maizzle/framework/releases/tag/v1.4.2)

**Comment by jsbrain** [comment] 2020-08-24 12:43
Amazing! Thank you! 🤓

**Comment by jsbrain** [comment] 2020-08-24 13:12
Not sure if it's just me but it actually does NOT work ...

I get the following error:

```
Failed to compile build_production/promotional.html
(node:26326) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/macpro/Code/maizzle/src/layouts/{{1 === 1 ? 'master' : 'master'}}.html'
```

Looks like it's not interpreted at all.

Reproduce as follow:

```
maizzle new https://github.com/maizzle/maizzle.git
cd maizzle
# -> Change first line in promotional.html
yarn production
```

**Comment by cossssmin** [comment] 2020-08-24 13:24
Sorry @jsbrain, I was referring to the original subject of this issue (`<outlook>` after `<if>`). 

Still looking into supporting expressions in the `src=""` attribute of `<extends>` - had something that I thought worked, but it was interfering with escaping expressions so I reverted it.

**Comment by jsbrain** [comment] 2020-08-24 14:18
Oh alright ... my bad 😀
