### ISSUE TITLE
Looping through array of objects passed from 'outside' will throw an error

### ISSUE THREAD

**Issue by schirliuradu** [maizzle/framework#336] opened 2020-10-22 13:40 UTC
- Maizzle Version: 2.3.0
- Node.js Version: 14.2.0

Hi Cosmin,

While playing a bit with maizzle events, i tried to reproduce the example you have in maizzle documentation, for ``beforeRender`` event. In that example you fetch some random data from somewhere, attach it to a config variable (preheader in that case) and then output it in a template / component.

I reproduced the same example, but with some more complex data comming from an api. I noticed that maizzle breakes building process when you pass down to the templates on ``page`` object some complex data, and with that i mean an array of objects. 

Consider this case:

You want to reach an api for fetching a list of items (could be random things), the api returns an array of objects, you save that result into a config variable that can be used down in a template. In that template, you istantiate a component (for example items-list-component) and pass to that component the ``{{ page.items }}`` parameter. Inside that component you'll check if page.items exists and you'll have a for loop (each) that will loop through all those items and print something. 

Well, if you reproduce this use case maizzle will not build anything, and there will be this error thrown by posthtml expressions
`` (node:10656) UnhandledPromiseRejectionWarning: Error: You must provide an array or object to loop through ``

The fact is that when you pass the same object, with the same structure directly into component `` locals `` without taking it from the api and reading it from `` page `` object it works properly. The error stack leads back to the ``index.js`` of  `` posthtml expressions `` plugin file that makes a control on the type of item that you are looping through.  
`
      if (typeof target !== 'object') {
        throw new Error('You must provide an array or object to loop through')
      } 
`

If you console log the ``target``, you can notice that this part runs twice: with the 2 cases i listed above you'll have

1. in case of data set in events in config and passed down to the template and then to the component: the first time the target will be a ``string`` and this breakes the build process because it needs an object, and this string will be something like this `` {{ page.items }} ``, while the second time you'll have the effective object that you are passing.

2. in case of data written directly in component locals (not coming from config file / events): in both times you'll have the effective value of the object, and this works fine.

Splitting things into templates / component to which you pass data from apis is a super powerful feature in maizzle, that's why i think it should work properly. 

Let me know if you can reproduce this issue. I hope i was clear enough, if not, let me know. And, thank you.

**Comment by cossssmin** [comment] 2020-10-22 15:23
This might be a `posthtml-expressions` bug or limitation, can you please create a repo that reproduces the error?

**Comment by schirliuradu** [comment] 2020-10-22 16:20
Of course. [Here](https://github.com/schirliuradu/maizzle-loop-bug-example) you have a link to an empty project that includes just a template file and istantiates a component that makes a for loop inside. The parameters comes from config file, not from api, but the issue is the same. Let me know what do you think about this. Thank you

**Comment by cossssmin** [comment] 2020-10-23 11:52
Check out https://github.com/schirliuradu/maizzle-loop-bug-example/pull/1

When using the `locals=""` attribute, you can only pass a JSON _string_, it doesn't evaluate expressions ([docs](https://maizzle.com/docs/components/#variables)) - so you can't pass in variables there, only hardcoded values. 

You can access the `page` object inside a component though, which is what I've done in that PR 👍

**Comment by schirliuradu** [comment] 2020-10-23 13:33
Hmm. Ok. Take a look please [here](https://github.com/schirliuradu/maizzle-loop-bug-example) again, i changed a bit the example, removing the for loop to avoid the error and render the template. Actually, if you give it a try, you can see that this `` "{{ page.something }}" `` passed into ``locals`` object works very well. The only problem is passing objects.

**Comment by cossssmin** [comment] 2020-10-23 13:54
`posthtml-modules`, the PostHTML plugin used for components, doesn't support passing objects:

https://github.com/posthtml/posthtml-modules/blob/c182bae68c0c31db257be929c2b7628ad715dbbb/index.js#L30-L36

As you can see, it uses `JSON.parse()` to parse the `locals` string, and since passing in an object results in an invalid JSON literal, it fails and returns an empty object.

Indeed, it works with `{{ }}` inside `''` because that is passed as a string and is actually evaluated inside the component. What I meant to say is that expressions can't be passed to be evaluated, so this can't work:

```html
<component src="src/components/example.html"  locals='{"items": {{ page.dataFromConfig }} }' />
```

... and, because it needs a valid JSON string, neither can this:

```html
<component src="src/components/example.html"  locals='{"items": page.dataFromConfig }' />
```

**Comment by cossssmin** [comment] 2020-10-23 14:37
If you're wondering why those 2 classes in your:

```html
<td class="{{ textColorClass }} {{ fontSizeClass }}">
```

... are not output in the compiled HTML, it's because PurgeCSS removes `text-gray-600` and `text-2xl` (that you define in `config.js`). It does that because they do not exist in the HTML files that are being scanned for selectors to preserve, when Tailwind is compiled - this happens _before_ PostHTML rendering takes place. Since those classes won't exist in the compiled Tailwind, `email-comb` will then remove them from your `class=""` attribute.

I assume this isn't the problem - as you noticed, they work fine.

Also, this works, you can loop over `items` inside `example.html`:

```html
<component src="example.html" locals='{"items": ["one", "two", "three"] }' />
```

And this also works:

```html
<!-- in template -->
<component src="example.html" locals='{"items": [{"name": "one"}, {"name": "two"}, {"name": "three"}] }' />

<!-- example.html component -->
<each loop="item, key in items">
  <tr>
    <td>{{ item.name }}</td>
  <tr>
</each>
```

If there's something I missed here and in my previous reply, please let me know and I'll try to help out.

**Comment by schirliuradu** [comment] 2020-10-25 18:04
Hi Cosmin, sorry for waiting. 

I know that passing an array directly into ``locals`` works fine, i think i've already tried everything. The only fact is that you can't pass an array from "outside" and you already understand what do i mean with this. The solution you proposed above (reading ``page.something`` directly into component without passing it from locals) is fine, but you know better than me that this overrides the ``locals`` object. I want to have some props that i pass into locals (like it could be some style or some classes or everything else) and read just the ``something`` property from ``page`` object. 

I know this is not possible at the moment, and i think this is a considerable limit of maizzle, the fact that you can not mix locals with things coming from page object.

**Comment by cossssmin** [comment] 2020-10-27 10:36
Yes, currently `posthtml-modules` doesn't have the feature you are asking for, I agree it would be nice to have... You can open an issue there and ask for it or help build it if you can 👍

**Comment by cossssmin** [comment] 2020-11-06 21:42
Closing this for now since it's technically possible, just not in a certain way.... yet. 

We'll get back to this depending on how things go with the modules plugin.

**Closed by cossssmin** 2020-11-06 21:42 UTC

**Comment by ZiggyMo** [comment] 2020-11-13 03:52
I was looking to upgrade from pre1.0 Maizzle but came across this limitation. Previously I was passing data into the template and using inside components via nunjucks. Was a bit surprised this isn't possible as it seems like pretty basic functionality for serious use. BTW Appreciate all the hard work that's been put into Maizzle thus far - just another +1 on feature request.
