### ISSUE TITLE
Nunjucks  Multilevel Template Inheritance is broken

### ISSUE THREAD

**Issue by j-mori** [maizzle/framework#69] opened 2019-12-09 16:15 UTC
- Maizzle Version: 0.4.4
- Node.js Version: 12.13.1

### Description:
Inheritance between templates doesn't work.

You can find the feature's documentation here:
Nunjucks (https://mozilla.github.io/nunjucks/templating.html#template-inheritance) 
and Jinja (https://jinja.palletsprojects.com/en/2.10.x/templates/#template-inheritance) 

This is caused by the code who extends the layout for all templates.

<code>
#node_modules/@maizzle/framework/src/generators/output/toDisk.js:60

html =  &#96;{% extends "${layout}" %}\n${frontMatter.body}&#96;
</code>

Some solutions could be to skip layout inclusion if the template contains `{% extends`, "layout" setting is explicitly set to false or a setting `doNotExtendsLayout` is set.

### Steps To Reproduce:
Extends a file or a template with another template and build.

**Comment by cossssmin** [comment] 2019-12-09 17:20
We could do something like:

```js
html = layout ? `{% extends "${layout}" %}\n${frontMatter.body}` : frontMatter.body
```

So then you'd set `layout: false` in the template's Front Matter to prevent this. Or as you mentioned, look for `{% extends` and do it without user intervention.

Perhaps I'm not thinking this through - can you please share a real-life scenario where you'd need a template to extend another template?

**Comment by cossssmin** [comment] 2019-12-09 17:46
Actually, can you please provide an example where it's broken, and how you'd expect it to be output?

**Comment by j-mori** [comment] 2019-12-10 09:30
> We could do something like:
> 
> ```js
> html = layout ? `{% extends "${layout}" %}\n${frontMatter.body}` : frontMatter.body
> ```
> So then you'd set `layout: false` in the template's Front Matter to prevent this. 

Just tested out,
<code>html = layout ? &#96;{% extends "${layout}" %}\n${frontMatter.body}&#96; : frontMatter.body</code>
we ll' do the trick but we should also change `toDisk.js:53`
<code>let layout = config.layout || config.build.layout</code> into 
<code>let layout = config.layout && config.build.layout</code> otherwise we can't set `layout= false` via Front Matter  because `false` we'll be ignored by the `||` operator.

>Or as you mentioned, look for `{% extends` and do it without user intervention.

I think, in addition, we should look for `{% extends ... %}` string in template because in nunjucks it's not possible anyway in just a single template extends multiple templates so its a good check to do.
Probably a regex like  `{%\s+?extends.+\s+?%}` should work but maybe it'll slow down compile time for big layouts?

> Perhaps I'm not thinking this through - can you please share a real-life scenario where you'd need a template to extend another template?

The scenario are various, i could have 2 similar newsletter template with just a couple of differences  in few blocks, in this case i could extends my newsletter template and redefine just the blocks with desired changes. With nunjucks this is possible at infinite sub-levels so i could extends a template who extends another template and so on. 
You could workaround with partials as well but it's just bad to lose a such cool feature who provide huge scalability  for a small problem.

**Comment by j-mori** [comment] 2019-12-10 09:39
> Actually, can you please provide an example where it's broken, and how you'd expect it to be output?

of course, take for example your default template transictional.njk, and wrap the "Confirm your email" button inside a ```{% block button %}{% endblock %}``` block.
now create another template transictional_account.njk:

<code>
{% extends "src/templates/transactional.njk" %}

{% block button %}Confirm your account{% endblock %}
</code>

Now my expectation are to get 2 differents, templates: one with "Confirm your email" button and another with "Confirm your account".
Instead i get a blank template becasue maizzle add the layout extensions on top of my tamplate, nullifing my extends line code.
Obviously this isn't the best feature case scenario becuse the button could be a compnent with a `text` parameter, but it's just to demostrate how and why the things breaks

**Comment by cossssmin** [comment] 2019-12-10 12:15
Thanks for the explanation, it's clear now.

I'm currently working on updating `toDisk()` to use the `toString()` method, to consolidate the codebase and make it easier to write tests in the future. I'd like to release this first (ideally this week or the next), and we can then handle this issue 👍

**Comment by j-mori** [comment] 2019-12-10 14:03
Perfect gonna follow the updates cause we are very interest to this framework!

**Comment by cossssmin** [comment] 2019-12-10 14:12
Btw you could use [Components](https://maizzle.com/docs/components/) for your buttons example - just pass in the text. Let me know if you want me to show you an example.

**Comment by j-mori** [comment] 2019-12-10 16:40
Yeah i know in that particularly case  components are probably a better way reach the result but they was just simple examples, when it comes to more complex templates where i would like to changes an entire code block instead of just a button (for exeample a column in a template with columns), template inheritance is a much better way to handle the case.

Anyway we should definetly fix this just because template inheritance it's a documented and cool feature that Nunjucks offers and at the moment is not working.

If you want i can  create a pull request with the changes mentioned above on the current maizzle version or if you prefer i can wait a couple of week for the new relase

**Comment by cossssmin** [comment] 2019-12-10 17:08
Yes, of course, the issue still stands - just wanted to have it mentioned. Would love to see a PR, but yeah please wait until I publish the new release. Thanks!

**Comment by cossssmin** [comment] 2019-12-11 14:18
Merged the PR that refactors `toDisk()`, can you work off of `master` or do you need me to publish a release? I'd honestly prefer if we publish a `v0.5.0` that includes both that and the inheritance fix.

**Comment by cossssmin** [comment] 2019-12-11 23:21
Fixed it, should work as expected now. Feel free to reopen if you spot any issues ✌

**Comment by j-mori** [comment] 2019-12-12 08:38
Thanks!

**Comment by cossssmin** [comment] 2019-12-12 12:09
Sorry, had to roll it back in `v0.5.1` because of several issues:

- `maizzle serve` was getting an `undefined` layout, so it was not using any
- all templates were using the same (default) layout, even if they extended a different one

I'm open to suggestions :)

**Comment by cossssmin** [comment] 2019-12-12 13:20
One possible solution would be to recursively recompile until there's no layout found.

For example, this works:

```js
html = `{% extends "${config.layout}" %}\n${html}`
html = nunjucks.renderString(html, { page: config, env: options.env, css: compiledCSS })

while (fm(html).attributes.layout) {
  const front = fm(html)
  html = `{% extends "${front.attributes.layout}" %}\n{% block template %}${front.body}{% endblock %}`
  html = nunjucks.renderString(html, { page: config, env: options.env, css: compiledCSS })
}
```

Downsides:

- you need to always use `{% block template %} ... {% endblock %}` in your templates, because by the last time it recompiles there is no block anymore and the final HTML will contain an empty `<body>`
- it slows the build process a bit; but if you don't do a lot of template->template extends, it's fine

**Comment by lowv-developer** [comment] 2019-12-12 14:15
I cant reproduce your example :/

**Comment by cossssmin** [comment] 2019-12-12 14:16
You need the `while` loop in the `toString()` method, have you added that locally? I haven't commited anything yet...

**Comment by lowv-developer** [comment] 2019-12-12 14:21
yes i did

i added this (i get error with {% extends "${config.layout}" %}:

>     const layout = config.layout || config.build.layout

and then below

> 

    ...const nunjucks = await NunjucksEnvironment.init()

    if (typeof options.beforeRender === 'function') {
      await options.beforeRender(nunjucks, config)
    }

    html = `{% extends "${layout}" %}\n${html}`
    html = nunjucks.renderString(html, { page: config, env: options.env, css: compiledCSS })

    while (fm(html).attributes.layout) {
      const front = fm(html)
      html = `{% extends "${front.attributes.layout}" %}\n{% block template %}${front.body}{% endblock %}`
      html = nunjucks.renderString(html, { page: config, env: options.env, css: compiledCSS })
    }

    html = ht..

**Comment by lowv-developer** [comment] 2019-12-12 14:26
my setup is:

```
<!-- src/layouts/default.njk -->
// default file

<!-- src/templates/trasactional.njk -->
---
layout: src/layouts/default.njk
---
{% block template %}
{% block button %}Confirm your email{% endblock %}
{% endblock %}


<!-- src/templates/transactional_account.njk -->
---
layout: src/templates/transactional.njk
---

{% block template %}
{% block button %}Confirm your account{% endblock %}
{% endblock %}
```

**Comment by cossssmin** [comment] 2019-12-12 14:30
Added https://github.com/maizzle/framework/commit/8bdb8ddc0f455fb560d33875aa2e3f89183ea987, make sure you're using `v0.5.1` and your `toString()` looks like in the `inheritance`  branch.

Otherwise files look alright, what command are you using?

**Comment by j-mori** [comment] 2019-12-12 14:36
> Sorry, had to roll it back in `v0.5.1` because of several issues:
> 
> * `maizzle serve` was getting an `undefined` layout, so it was not using any
> * all templates were using the same (default) layout, even if they extended a different one
> 
> I'm open to suggestions :)

hi! Wasn't the problem caused by the bad layout assignment?
just figured out that my advice to use
<code>let layout = config.layout && config.build.layout </code> was just bad.
do you think something like this will solve the issue?
<code>
let layout = config.layout != null ?  config.layout : config.build.layout 
</code>

**Comment by lowv-developer** [comment] 2019-12-12 14:37
"@maizzle/framework": "^0.5.1",

maizzle serve

i copy/paste the raw file from "Rework template inheritance"

ex. 
In src/templates/transactional_account.njk 
I only see the Confirm your account text (no template). Im seeing the all the head stuff in view source

**Comment by cossssmin** [comment] 2019-12-12 14:44
> hi! Wasn't the problem caused by the bad layout assignment?

Unfortunately no, you could extend as many levels deep as you'd want, so each level will contain a different `layout`. In order to go up the chain and reach the Layout, while actually rendering block contents, you need to re-render the template, talking the newly-found Front Matter into account.

**Comment by j-mori** [comment] 2019-12-12 14:45
> Added [8bdb8dd](https://github.com/maizzle/framework/commit/8bdb8ddc0f455fb560d33875aa2e3f89183ea987), make sure you're using `v0.5.1` and your `toString()` looks like in the `inheritance` branch. You shouldn't get any error with `config.layout`.
> 
> Otherwise files look alright, what command are you using?

I got an

> Added [8bdb8dd](https://github.com/maizzle/framework/commit/8bdb8ddc0f455fb560d33875aa2e3f89183ea987), make sure you're using `v0.5.1` and your `toString()` looks like in the `inheritance` branch. You shouldn't get any error with `config.layout`.
> 
> Otherwise files look alright, what command are you using?

i get an error `Error: template not found: undefined`, `config.layout` is undefined

**Comment by lowv-developer** [comment] 2019-12-12 14:49
you need to declare layout in every template!

> > Added [8bdb8dd](https://github.com/maizzle/framework/commit/8bdb8ddc0f455fb560d33875aa2e3f89183ea987), make sure you're using `v0.5.1` and your `toString()` looks like in the `inheritance` branch. You shouldn't get any error with `config.layout`.
> > Otherwise files look alright, what command are you using?
> 
> i get an error `Error: template not found: undefined`, `config.layout` is undefined

**Comment by cossssmin** [comment] 2019-12-12 14:55
> i get an error `Error: template not found: undefined`, `config.layout` is undefined

Just tested with your exact files, it works perfectly fine. Not sure what's causing it for you.

> you need to declare layout in every template!

Right, `src/layouts/default.njk` is no longer automagically set as the Layout being extended, you need to extend it in your Template.

**Comment by lowv-developer** [comment] 2019-12-12 14:57
"automagically" is always better! :D

**Comment by j-mori** [comment] 2019-12-12 15:02
> Right, `src/layouts/default.njk` is no longer automagically set as the Layout being extended, you need to extend it in your Template.

The problem was this.

I wasn't setting template for every default template via FM and miazzle was crashing, so is this  inteded?

**Comment by j-mori** [comment] 2019-12-12 15:08
> "@maizzle/framework": "^0.5.1",
> 
> maizzle serve
> 
> i copy/paste the raw file from "Rework template inheritance"
> 
> ex.
> In src/templates/transactional_account.njk
> I only see the Confirm your account text (no template). Im seeing the all the head stuff in view source

Declaring layout in every template make maizzle compile but i get the same result:
transiciotnal.njk work fine
transictional_account.njk show only declared block as plain text + FM text of the extended template, layout/default.njk seems not being loaded

**Comment by cossssmin** [comment] 2019-12-12 15:28
You're both probably running into a caching issue or something, just tested this and it works with the default layout:

`src/templates/first.njk` :

```nunjucks
---
layout: src/layouts/default.njk
---

{% block template %}
Parent Template
{% block button %}First{% endblock %}
{% endblock %}
```

`src/templates/second.njk` :

```nunjucks
---
layout: src/templates/first.njk
---

{% block template %}
{% block button %}Second{% endblock %}
{% endblock %}
```

`{{ super() }}` added in the template block of `second.njk` also works.

**Comment by cossssmin** [comment] 2019-12-12 16:02
So to get inheritance working properly, the trade-off here is to always have to specify the Layout you're extending from a Template.

I believe I had it work automatically being inspired by the Jigsaw static site generator, which powered the original Maizzle (can't remember if it was a feature, or just something you could just do).

Since we have no better solution, I think we'll go with this - it's a very small trade-off to make for what you get in return.

**Comment by cossssmin** [comment] 2019-12-12 16:35
I tried, it, answered there in #74 . Not only does it not compile that template that extends a template, but I don't want users to have to add workarounds like this, with `false` and `{% extends %}`.

Thanks for the PR, but I think I'm just going to make specifying a `layout:` mandatory. It's not a big deal and it doesn't do any magic stuff, which I think is better.

**Comment by cossssmin** [comment] 2019-12-12 16:55
There's obviously still an issue with using `render()` without extending a Layout (simply render a string), working on a solution...

**Comment by cossssmin** [comment] 2019-12-12 17:19
Fixed it, will publish soon. @lowv-developer managed to preserve the 'automagic' of layout extending - you should only be required to specify the `layout` key only if your template is being extended by another template.

**Comment by cossssmin** [comment] 2019-12-12 17:34
Please check [v0.5.2](https://github.com/maizzle/framework/releases/tag/v0.5.2), it should have fixed the issues.

**Comment by j-mori** [comment] 2019-12-13 09:17
Thanks for the fix! just tested out and it seems working pretty fine, but i have another related small problem, maybe i m doing something wrong but seems that the main layout doesn't get compiled.

This is my setup with defaults templates:

src/templates/transactional.njk:
 added
```
---
layout: src/layouts/default.njk
---
```
and wrapped command inside a block
```
{% block cta %} Confirm email address{% endblock %}
```

src/templates/transactional_account.njk:
```
---
layout: src/templates/transactional.njk
---
{% block cta %} Confirm your account{% endblock %}

```


The expected result would be two identical html with differents commands text, but in `transactional_account.njk`  some class miss inside `<html>,<body>` tags, probably layout didn't get compiled as should?

**Comment by cossssmin** [comment] 2019-12-13 10:38
Will need to test, but I have a hunch this is purgeCSS or email-comb removing classes. Might have to do with the recursive re-rendering.

This is for the `maizzle build` command right?

**Comment by j-mori** [comment] 2019-12-13 17:02
No i m having the issue with miazzle serve, did'nt tested `build` command

**Comment by lowv-developer** [comment] 2019-12-14 15:47
everything seems to be working fine!

```
<!-- src/templates/transactional_account.njk -->
---
title: trasactional
layout: src/templates/transactional.njk
bodyClass: bg-gray-200 h-full
htmlClass: bg-gray-200 h-full
---


{% block button %}Confirm your account{% endblock %}
```

**Comment by lowv-developer** [comment] 2019-12-14 15:51
> No i m having the issue with miazzle serve, did'nt tested `build` command

try to delete the folder @maizzle and npm install

when there is inheritance you need to declare layout in every level.

the layout is optional when you have only one level (without inheritance)

**Comment by cossssmin** [comment] 2019-12-16 10:26
> when there is inheritance you need to declare layout in every level.

This. You need to always declare the layout you're extending, if you use inheritance (extending a template from a template). Just tested and it works as expected, so I'll close this as resolved - feel free to reopen if you spot other issues with it. And big thanks to both of you for your help ✌

**Closed by cossssmin** 2019-12-16 10:26 UTC
