### ISSUE TITLE
serve randomly stops working with "received empty string"

### ISSUE THREAD

**Issue by Xeevis** [maizzle/framework#428] opened 2021-04-09 15:43 UTC
- Maizzle Version: 3.3.0
- Node.js Version: 15.12.0
- TailwindCSS Version: 2.1.1

Every time I save template file when browsersync is running there is a good chance whole thing will crash with error (even if I make no changes). This is extremely annoying because it takes good 10 seconds to run again and happens with clean [starter template](https://github.com/maizzle/maizzle). It happens so randomly that it looks like race condition.

![image](https://user-images.githubusercontent.com/5835044/114204583-a38d0800-9959-11eb-8870-8726f615fbb7.png)

**Comment by Xeevis** [comment] 2021-04-09 15:52
Yes it's definitely race condition, if I reduce size of the template HTML it crashes less often, following code won't throw at all.
```html
<extends src="src/layouts/master.html">
  <block name="template">
    <b>hello world!</b>
  </block>
</extends>
```
But saving the default `promotional.html` will crash every time.

**Comment by damian-perez-globant** [comment] 2021-04-09 17:47
Same here, this error is happening every 2 o 3 continous saving in vscode (running maizzle serve on the background)

**Comment by cossssmin** [comment] 2021-04-13 14:03
I'm not able to reproduce this with the default starter, however 10 seconds to run `maizzle serve` again doesn't sound right and might be an indication that something is slowing down either Browsersync or even your machine.

I think we could do better and refactor [this part](https://github.com/maizzle/framework/blob/b2cebfba250778a2746bc27868c9f6093b146152/src/index.js#L67-L80), but from my tests it doesn't make any difference if we don't combine await with callbacks.

**Comment by Xeevis** [comment] 2021-04-13 14:59
@cossssmin I've discovered the culprit. It's incompatibility with VS Code extension [Headwind](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind) (which is kind of essential when working with TailwindCSS classes). Moment it's enabled it starts racing. With larger code like `promotional.html` outright crashing when saved from within VS Code with the extension enabled (if saved externally it's fine).

Workaround is to turn off "Headwind: Run on Save" 
```json5
// .vscode/settings.json
{
  "headwind.runOnSave": false
}
```
I suspect `to-string.js` is called before sorting is complete resulting in it getting empty string. Small markup is sorted faster and therefore makes it in time. Not sure if it's Maizzle, Browsersync or Headwind issue though .,.

**Comment by cossssmin** [comment] 2021-04-13 15:57
It sounds like that extension might be saving/overwriting the file as empty until it finishes sorting classes or something. That would explain why `to-string.js` receives an empty string to parse and why it's more proeminent with larger files.

Closing since it's not a Maizzle bug per-se, but feel free to reopen if you have new info.

**Closed by cossssmin** 2021-04-13 15:57 UTC
Labels: bug
